import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNavBar from './components/sidenavbar/sidenavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNavBar/>
        <div className='main-screen'>
          <div className='main-screen-addornments'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
